name: test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install
        run: |
          yarn install
      - name: test
        run: |
          npx jest
      - name: regsuit
        run: |
          npx reg-suit run
        env:
          AWS_SECRET_ACCESS_KEY: ${{ seacret.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ seacret.AWS_ACCESS_KEY_ID }}
